name: Python formatter (isort and black)

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install isort and black
        run: |
          python -m pip install --upgrade pip
          pip install isort black
          
      - name: Run isort
        run: isort .

      - name: Run black
        run: black .

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -z $(git status --porcelain) ]; then echo "true"; else echo "false"; fi)      
      - name: GitHub credentials
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: "RoTo CI Bot"
          email: "jbriegal@cantab.net"
          actor: "roto-ci-bot"
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Push changes
        if: steps.git-check.outputs.modified == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
        run: |
          git add .
          git commit -am "fixup: Format Python code with Black and isort"
          git push

